version: 2.0

phases:

  pre_build:

    commands:

      - echo Mule build-deployment phase initiated...

      - mvn test

  build:

    commands:

      - echo Build started on `date`

      - mvn package

  post_build:

    commands:

      - echo Build completed on `date`

      - mvn deploy -DmuleDeploy -Dcloud.env=Sandbox -Danypoint.businessGroup=<BusinessGroup> -Dcloudhub.workerType=Small -DcloudhubAppName=ramlapikitmule4 -Dmule.version=4.1.5 -Dcloud.user=<username> -Dcloud.password=<****>
